// IMPORTANT: This file is auto-generated by FlutterFire CLI.
// Run the following commands to generate it:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID --platforms=android,ios
//
// After running the above, this file will be replaced with your actual Firebase config.
// DO NOT commit this placeholder to production.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run: flutterfire configure --project=YOUR_PROJECT_ID',
        );
    }
  }

  // ⚠️  PLACEHOLDER VALUES — Replace by running: flutterfire configure
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYuqeKOBTKPa-5z12K76To34NsdUy_nM8',
    appId: '1:1093597179954:android:0a98f97f4c1f3c18468c2b',
    messagingSenderId: '1093597179954',
    projectId: 'fleetcheek',
    storageBucket: 'fleetcheek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.FleetCheck.Evs',
  );
}
