import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import '../../core/constants/app_colors.dart';
import '../../core/constants/app_strings.dart';
import '../../models/inspection_model.dart';
import '../../repositories/inspection_repository.dart';
import '../../routes/app_router.dart';

class SubmissionSuccessScreen extends StatefulWidget {
  final InspectionResult result;
  const SubmissionSuccessScreen({super.key, required this.result});

  @override
  State<SubmissionSuccessScreen> createState() => _SubmissionSuccessScreenState();
}

class _SubmissionSuccessScreenState extends State<SubmissionSuccessScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _aniController;
  late Animation<double> _scaleAnim;
  late Animation<double> _fadeAnim;

  bool _isDownloading = false;
  bool _isSharing     = false;

  @override
  void initState() {
    super.initState();
    _aniController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 700),
    );
    _scaleAnim = CurvedAnimation(parent: _aniController, curve: Curves.elasticOut);
    _fadeAnim  = CurvedAnimation(parent: _aniController, curve: Curves.easeIn);
    _aniController.forward();
  }

  @override
  void dispose() {
    _aniController.dispose();
    super.dispose();
  }

  Future<void> _downloadPdf() async {
    setState(() => _isDownloading = true);
    try {
      // In production: call API to get PDF bytes, then save using path_provider + open_file
      await Future.delayed(const Duration(seconds: 2)); // simulate
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Inspection report downloaded successfully.'),
          backgroundColor: AppColors.secondary,
        ),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(AppStrings.pdfFailed),
          backgroundColor: AppColors.danger,
        ),
      );
    } finally {
      if (mounted) setState(() => _isDownloading = false);
    }
  }

  Future<void> _shareReport() async {
    setState(() => _isSharing = true);
    try {
      final r = widget.result;
      final text = '''
FleetCheck Inspection Report

Inspection ID:    ${r.inspectionId}
Vehicle:          ${r.vehicleNumber}
Type:             ${r.inspectionType == 'pre_trip' ? 'Pre-Trip' : 'Post-Trip'} Inspection
Date & Time:      ${DateFormat('MM/dd/yyyy hh:mm a').format(r.submittedAt)}
GPS Location:     ${r.gpsLocation?.address ?? '—'}
Status:           ${r.status.toUpperCase()}

Generated by FleetCheck — Inspect. Verify. Drive with Confidence.
      ''';
      await Share.share(text, subject: 'FleetCheck Inspection Report – ${r.inspectionId}');
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(AppStrings.shareFailed),
          backgroundColor: AppColors.danger,
        ),
      );
    } finally {
      if (mounted) setState(() => _isSharing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final r         = widget.result;
    final isPreTrip = r.inspectionType == 'pre_trip';

    // Block back navigation — submission is final
    return PopScope(
      canPop: false,
      child: Scaffold(
        backgroundColor: AppColors.background,
        body: SafeArea(
          child: SingleChildScrollView(
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                // ✅ Animated success icon
                ScaleTransition(
                  scale: _scaleAnim,
                  child: Container(
                    width: 100,
                    height: 100,
                    decoration: BoxDecoration(
                      gradient: AppColors.greenGradient,
                      shape: BoxShape.circle,
                      boxShadow: [
                        BoxShadow(
                          color: AppColors.secondary.withOpacity(0.35),
                          blurRadius: 28,
                          spreadRadius: 4,
                        ),
                      ],
                    ),
                    child: const Icon(Icons.check_rounded, color: Colors.white, size: 56),
                  ),
                ),
                const SizedBox(height: 24),

                // Title
                FadeTransition(
                  opacity: _fadeAnim,
                  child: Column(
                    children: [
                      const Text(
                        AppStrings.submissionSuccess,
                        style: TextStyle(fontSize: 20, fontWeight: FontWeight.w800, color: AppColors.secondary),
                        textAlign: TextAlign.center,
                      ),
                      const SizedBox(height: 8),
                      const Text(
                        'Your inspection report has been recorded.',
                        style: TextStyle(fontSize: 14, color: AppColors.textSecondary),
                        textAlign: TextAlign.center,
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 28),

                // Details card
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    color: AppColors.surface,
                    borderRadius: BorderRadius.circular(14),
                    border: Border.all(color: AppColors.border),
                    boxShadow: [
                      BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 12, offset: const Offset(0, 4)),
                    ],
                  ),
                  child: Column(
                    children: [
                      // Inspection ID
                      _DetailItem(
                        icon: Icons.confirmation_number_outlined,
                        label: 'Inspection ID',
                        value: r.inspectionId,
                        valueStyle: const TextStyle(
                          fontWeight: FontWeight.w800,
                          fontSize: 16,
                          color: AppColors.primary,
                          letterSpacing: 0.5,
                        ),
                      ),
                      const Divider(height: 20),
                      _DetailItem(
                        icon: Icons.local_shipping_outlined,
                        label: 'Vehicle Number',
                        value: r.vehicleNumber,
                      ),
                      const Divider(height: 20),
                      _DetailItem(
                        icon: isPreTrip ? Icons.wb_sunny_outlined : Icons.nights_stay_outlined,
                        label: 'Inspection Type',
                        value: isPreTrip ? 'Pre-Trip Inspection' : 'Post-Trip Inspection',
                        valueColor: isPreTrip ? AppColors.secondary : AppColors.primary,
                      ),
                      const Divider(height: 20),
                      _DetailItem(
                        icon: Icons.calendar_today_outlined,
                        label: 'Date & Time',
                        value: DateFormat('MM/dd/yyyy hh:mm a').format(r.submittedAt),
                      ),
                      const Divider(height: 20),
                      _DetailItem(
                        icon: Icons.location_on_outlined,
                        label: 'GPS Location',
                        value: r.gpsLocation?.address ?? '—',
                        multiLine: true,
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),

                // Download PDF
                SizedBox(
                  width: double.infinity,
                  height: 52,
                  child: ElevatedButton.icon(
                    onPressed: _isDownloading ? null : _downloadPdf,
                    icon: _isDownloading
                        ? const SizedBox(width: 18, height: 18, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2.5))
                        : const Icon(Icons.picture_as_pdf_rounded, size: 20),
                    label: Text(_isDownloading ? 'Generating PDF...' : 'Download PDF', style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w600)),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFFDC2626),
                      foregroundColor: Colors.white,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                    ),
                  ),
                ),
                const SizedBox(height: 10),

                // Share Report
                SizedBox(
                  width: double.infinity,
                  height: 52,
                  child: OutlinedButton.icon(
                    onPressed: _isSharing ? null : _shareReport,
                    icon: _isSharing
                        ? const SizedBox(width: 18, height: 18, child: CircularProgressIndicator(strokeWidth: 2.5))
                        : const Icon(Icons.share_outlined, size: 20),
                    label: Text(_isSharing ? 'Sharing...' : 'Share Report', style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w600)),
                  ),
                ),
                const SizedBox(height: 10),

                // Return to Dashboard
                SizedBox(
                  width: double.infinity,
                  height: 52,
                  child: ElevatedButton.icon(
                    onPressed: () => context.go(AppRoutes.dashboard),
                    icon: const Icon(Icons.home_rounded, size: 20),
                    label: const Text('Return to Dashboard', style: TextStyle(fontSize: 15, fontWeight: FontWeight.w600)),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.primary,
                      foregroundColor: Colors.white,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _DetailItem extends StatelessWidget {
  final IconData icon;
  final String label;
  final String value;
  final Color? valueColor;
  final TextStyle? valueStyle;
  final bool multiLine;

  const _DetailItem({
    required this.icon,
    required this.label,
    required this.value,
    this.valueColor,
    this.valueStyle,
    this.multiLine = false,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Icon(icon, size: 18, color: AppColors.textSecondary),
        const SizedBox(width: 12),
        Expanded(
          child: multiLine
              ? Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                  Text(label, style: const TextStyle(fontSize: 12, color: AppColors.textSecondary)),
                  const SizedBox(height: 2),
                  Text(value, style: valueStyle ?? TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: valueColor ?? AppColors.textPrimary, height: 1.4)),
                ])
              : Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
                  Text(label, style: const TextStyle(fontSize: 12, color: AppColors.textSecondary)),
                  Flexible(
                    child: Text(value, textAlign: TextAlign.right,
                        style: valueStyle ?? TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: valueColor ?? AppColors.textPrimary)),
                  ),
                ]),
        ),
      ],
    );
  }
}
